spring.application.name=disaster-relief-portal-backend
spring.security.user.name=admin
spring.security.user.password=password
# Enable/Disable restart
spring.devtools.restart.enabled=true

# Exclude specific paths from triggering a restart (like your static frontend files)
spring.devtools.restart.exclude=static/**,public/**